"""
RustAuditAI PDF Report Generator.
Generates publication-grade, self-contained executive code quality & vulnerability audit reports
using ReportLab Platypus and custom canvas pagination.
Complies with SRS §4.6.5 (PDF and Report Export).
"""

import html
import io
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that accurately calculates total page numbers
    and stamps running headers and footers on every page.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_decorations(self, num_pages: int):
        self.saveState()

        # Running Header (on pages after the first or on all pages)
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))
        self.drawString(36, 756, "RustAuditAI — Rust Quality Index (RQI) & Security Audit")

        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#94a3b8"))
        self.drawRightString(612 - 36, 756, "Confidential — Static Analysis Report")

        # Header rule
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.75)
        self.line(36, 748, 612 - 36, 748)

        # Footer rule
        self.line(36, 42, 612 - 36, 42)

        # Running Footer
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        self.drawString(36, 30, "Generated by RustAuditAI Code Property Graph (CPG) Pipeline v0.1.0")

        page_str = f"Page {self._pageNumber} of {num_pages}"
        self.setFont("Helvetica-Bold", 8)
        self.drawRightString(612 - 36, 30, page_str)

        self.restoreState()


class RustAuditPDFReportGenerator:
    """
    Builds publication-grade executive audit PDF documents.
    """

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._init_custom_styles()

    def _init_custom_styles(self):
        normal = self.styles["Normal"]

        # Color Palette constants
        self.C_PRIMARY = colors.HexColor("#0f172a")     # Deep slate / navy
        self.C_SECONDARY = colors.HexColor("#1e293b")   # Slate 800
        self.C_ACCENT = colors.HexColor("#0284c7")      # Sky blue
        self.C_MUTED = colors.HexColor("#64748b")       # Slate 500
        self.C_BORDER = colors.HexColor("#e2e8f0")      # Slate 200
        self.C_LIGHT_BG = colors.HexColor("#f8fafc")    # Slate 50
        self.C_WHITE = colors.HexColor("#ffffff")

        # Severity Colors
        self.C_SEV_CRITICAL = colors.HexColor("#b91c1c")
        self.C_SEV_HIGH = colors.HexColor("#c2410c")
        self.C_SEV_MEDIUM = colors.HexColor("#b45309")
        self.C_SEV_LOW = colors.HexColor("#2563eb")
        self.C_SEV_PASS = colors.HexColor("#15803d")

        self.style_doc_title = ParagraphStyle(
            "DocTitle",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=self.C_WHITE,
        )

        self.style_doc_subtitle = ParagraphStyle(
            "DocSubtitle",
            parent=normal,
            fontName="Helvetica",
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#94a3b8"),
        )

        self.style_section_heading = ParagraphStyle(
            "SectionHeading",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=self.C_PRIMARY,
            spaceAfter=6,
        )

        self.style_subheading = ParagraphStyle(
            "Subheading",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            textColor=self.C_SECONDARY,
        )

        self.style_body = ParagraphStyle(
            "ReportBody",
            parent=normal,
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            textColor=colors.HexColor("#334155"),
        )

        self.style_body_bold = ParagraphStyle(
            "ReportBodyBold",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11.5,
            textColor=self.C_PRIMARY,
        )

        self.style_meta_label = ParagraphStyle(
            "MetaLabel",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9.5,
            textColor=colors.HexColor("#64748b"),
        )

        self.style_meta_val = ParagraphStyle(
            "MetaVal",
            parent=normal,
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=self.C_PRIMARY,
        )

        self.style_score_big = ParagraphStyle(
            "ScoreBig",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=26,
            leading=28,
            alignment=1,  # Center
            textColor=self.C_PRIMARY,
        )

        self.style_grade_badge = ParagraphStyle(
            "GradeBadge",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            alignment=1,
            textColor=self.C_WHITE,
        )

        self.style_code = ParagraphStyle(
            "CodeBlock",
            parent=normal,
            fontName="Courier",
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#0f172a"),
        )

        self.style_cwe_badge = ParagraphStyle(
            "CWEBadge",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=self.C_WHITE,
        )

        self.style_table_head = ParagraphStyle(
            "TableHead",
            parent=normal,
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=self.C_WHITE,
        )

        self.style_table_cell = ParagraphStyle(
            "TableCell",
            parent=normal,
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor("#1e293b"),
        )

        self.style_remediation = ParagraphStyle(
            "RemediationText",
            parent=normal,
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor("#0369a1"),
        )

    def _safe_text(self, text: Any) -> str:
        """Escape text for safe inclusion inside ReportLab Paragraphs."""
        if text is None:
            return ""
        return html.escape(str(text))

    def _get_grade_color(self, grade: str) -> colors.HexColor:
        grade_upper = str(grade).upper()
        if "A" in grade_upper:
            return colors.HexColor("#16a34a")  # Green
        elif "B" in grade_upper:
            return colors.HexColor("#0284c7")  # Sky blue
        elif "C" in grade_upper:
            return colors.HexColor("#d97706")  # Amber
        else:
            return colors.HexColor("#dc2626")  # Red

    def _get_severity_color(self, sev: str) -> colors.HexColor:
        s = str(sev).upper()
        if s == "CRITICAL":
            return self.C_SEV_CRITICAL
        elif s == "HIGH":
            return self.C_SEV_HIGH
        elif s == "MEDIUM":
            return self.C_SEV_MEDIUM
        elif s == "LOW":
            return self.C_SEV_LOW
        return self.C_SEV_PASS

    def generate(
        self,
        audit_data: Dict[str, Any],
        filename: Optional[str] = None,
        source_code: Optional[str] = None,
    ) -> bytes:
        """
        Generate a complete executive PDF audit report.
        Accepts either a single function audit dict or a multi-function audit response dict.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=48,
            bottomMargin=48,
        )

        story = []

        # Determine if payload has multiple functions or is a single function
        functions = []
        target_filename = filename or audit_data.get("filename", "rust_subroutine.rs")

        if "functions" in audit_data and isinstance(audit_data["functions"], list):
            functions = audit_data["functions"]
        elif "name" in audit_data and "rqi" in audit_data:
            functions = [audit_data]
        elif "current_function" in audit_data:
            functions = [audit_data["current_function"]]
        else:
            # Wrap whatever dict we have
            functions = [audit_data]

        timestamp_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Add Header Banner
        story.extend(self._build_header_banner(target_filename, timestamp_str, len(functions)))
        story.append(Spacer(1, 12))

        # If multiple functions, add high-level summary table first
        if len(functions) > 1:
            story.extend(self._build_multi_function_summary(functions))
            story.append(Spacer(1, 14))

        # Render sections for each function
        for i, fn_data in enumerate(functions):
            if i > 0:
                story.append(PageBreak())

            story.extend(self._build_function_report(fn_data, target_filename, timestamp_str))

        # Build PDF document
        doc.build(story, canvasmaker=NumberedCanvas)
        return buffer.getvalue()

    def _build_header_banner(
        self, filename: str, timestamp_str: str, function_count: int
    ) -> List[Any]:
        """Creates the dark top banner with RustAuditAI branding and metadata."""
        col1_content = [
            Paragraph("RUSTAUDIT AI", self.style_doc_title),
            Spacer(1, 2),
            Paragraph("Automated Rust Quality Index (RQI) & MITRE CWE Static Audit", self.style_doc_subtitle),
        ]

        col2_content = [
            Paragraph(f"<b>Target File:</b> {self._safe_text(filename)}", self.style_doc_subtitle),
            Paragraph(f"<b>Audit Date:</b> {self._safe_text(timestamp_str)}", self.style_doc_subtitle),
            Paragraph(f"<b>Functions Analyzed:</b> {function_count}", self.style_doc_subtitle),
        ]

        banner_table = Table(
            [[col1_content, col2_content]],
            colWidths=[330, 210],
            style=[
                ("BACKGROUND", (0, 0), (-1, -1), self.C_PRIMARY),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 14),
                ("RIGHTPADDING", (0, 0), (-1, -1), 14),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ],
        )

        return [banner_table]

    def _build_multi_function_summary(self, functions: List[Dict[str, Any]]) -> List[Any]:
        """Summary table when multiple functions are analyzed."""
        story = [
            Paragraph("Subroutine Portfolio Summary", self.style_section_heading),
            Spacer(1, 4),
        ]

        headers = ["Subroutine", "Lines", "RQI Score", "Grade", "Weaknesses", "Status"]
        rows = [
            [Paragraph(f"<b>{h}</b>", self.style_table_head) for h in headers]
        ]

        for fn in functions:
            rqi_info = fn.get("rqi", {})
            score = rqi_info.get("rqi_score", 0.0)
            grade = rqi_info.get("grade", "N/A")
            cwe_tags = fn.get("cwe_tags", []) or rqi_info.get("cwe_tags", [])
            line_str = f"{fn.get('line_start', 1)} - {fn.get('line_end', '-')}"
            status = "Clean" if len(cwe_tags) == 0 else f"{len(cwe_tags)} finding(s)"

            rows.append([
                Paragraph(f"<code>{self._safe_text(fn.get('name', 'subroutine'))}</code>", self.style_table_cell),
                Paragraph(line_str, self.style_table_cell),
                Paragraph(f"<b>{score:.1f}</b>", self.style_table_cell),
                Paragraph(self._safe_text(grade[:8]), self.style_table_cell),
                Paragraph(str(len(cwe_tags)), self.style_table_cell),
                Paragraph(status, self.style_table_cell),
            ])

        summary_table = Table(
            rows,
            colWidths=[140, 70, 70, 90, 80, 90],
            style=[
                ("BACKGROUND", (0, 0), (-1, 0), self.C_SECONDARY),
                ("GRID", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [self.C_WHITE, self.C_LIGHT_BG]),
            ],
        )
        story.append(summary_table)
        return story

    def _build_function_report(
        self, fn_data: Dict[str, Any], filename: str, timestamp_str: str
    ) -> List[Any]:
        """Builds all sections for a single function audit."""
        story = []

        fn_name = fn_data.get("name", "subroutine")
        line_start = fn_data.get("line_start", 1)
        line_end = fn_data.get("line_end", line_start)
        rqi_info = fn_data.get("rqi", {})
        rqi_score = float(rqi_info.get("rqi_score", 0.0))
        grade = str(rqi_info.get("grade", "N/A"))
        penalty_applied = bool(rqi_info.get("penalty_applied", False))
        penalty_reasons = rqi_info.get("penalty_reasons", [])
        cpg_summary = fn_data.get("cpg_summary", {})
        cwe_summary = fn_data.get("cwe_summary", {}) or rqi_info.get("cwe_summary", {})
        cwe_tags = fn_data.get("cwe_tags", []) or rqi_info.get("cwe_tags", [])

        # Subroutine Identification Bar
        fn_title_text = f"Function Audit: <code>fn {self._safe_text(fn_name)}()</code>"
        story.append(Paragraph(fn_title_text, self.style_section_heading))

        qualifiers = []
        if fn_data.get("visibility"):
            qualifiers.append(fn_data["visibility"])
        if fn_data.get("is_unsafe"):
            qualifiers.append("unsafe")
        if fn_data.get("is_async"):
            qualifiers.append("async")
        qualifier_str = " ".join(qualifiers) if qualifiers else "private (default)"

        meta_table = Table(
            [
                [
                    Paragraph("<b>Qualifiers:</b>", self.style_meta_label),
                    Paragraph(self._safe_text(qualifier_str), self.style_meta_val),
                    Paragraph("<b>Source Lines:</b>", self.style_meta_label),
                    Paragraph(f"Line {line_start} to {line_end}", self.style_meta_val),
                    Paragraph("<b>Target File:</b>", self.style_meta_label),
                    Paragraph(self._safe_text(filename), self.style_meta_val),
                ]
            ],
            colWidths=[65, 115, 75, 105, 70, 110],
            style=[
                ("BACKGROUND", (0, 0), (-1, -1), self.C_LIGHT_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ],
        )
        story.append(meta_table)
        story.append(Spacer(1, 10))

        # -------------------------------------------------------------
        # Section 1: Executive RQI Scorecard & Vectors
        # -------------------------------------------------------------
        story.extend(
            self._build_scorecard_and_vectors(
                rqi_score, grade, penalty_applied, penalty_reasons, rqi_info
            )
        )
        story.append(Spacer(1, 12))

        # -------------------------------------------------------------
        # Section 2: MITRE CWE Weaknesses Summary Strip
        # -------------------------------------------------------------
        story.extend(self._build_cwe_summary_strip(cwe_summary, cwe_tags))
        story.append(Spacer(1, 12))

        # -------------------------------------------------------------
        # Section 3: Quality Deductions & Weakness Catalog
        # -------------------------------------------------------------
        story.extend(self._build_deductions_catalog(rqi_info, cwe_tags))
        story.append(Spacer(1, 12))

        # -------------------------------------------------------------
        # Section 4: Code Property Graph (CPG) & Topology Metrics
        # -------------------------------------------------------------
        story.extend(self._build_cpg_metrics_section(cpg_summary, fn_data))
        story.append(Spacer(1, 12))

        # -------------------------------------------------------------
        # Section 5: Explainable AI (XAI) Refactoring Candidate (if present)
        # -------------------------------------------------------------
        xai_report = fn_data.get("xai_report")
        if xai_report and isinstance(xai_report, dict) and not xai_report.get("error"):
            story.extend(self._build_xai_section(xai_report))

        return story

    def _build_scorecard_and_vectors(
        self,
        rqi_score: float,
        grade: str,
        penalty_applied: bool,
        penalty_reasons: List[str],
        rqi_info: Dict[str, Any],
    ) -> List[Any]:
        """Renders the executive score card alongside vector metrics."""
        grade_color = self._get_grade_color(grade)

        # Left Column: Big Score Badge & Penalty details
        left_cell_elements = [
            Paragraph("COMPOSITE RQI SCORE", self.style_meta_label),
            Spacer(1, 4),
            Paragraph(f"{rqi_score:.1f} <font size=13 color='#64748b'>/ 100</font>", self.style_score_big),
            Spacer(1, 6),
            Table(
                [[Paragraph(self._safe_text(grade), self.style_grade_badge)]],
                colWidths=[180],
                style=[
                    ("BACKGROUND", (0, 0), (-1, -1), grade_color),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ],
            ),
        ]

        if penalty_applied:
            reasons_txt = "<br/>• ".join([self._safe_text(r) for r in penalty_reasons])
            penalty_box = Table(
                [
                    [
                        Paragraph(
                            f"<b>Penalty Warning:</b><br/>• {reasons_txt}",
                            ParagraphStyle("PenTxt", parent=self.style_body, textColor=self.C_SEV_CRITICAL, fontSize=7.5, leading=9.5),
                        )
                    ]
                ],
                colWidths=[180],
                style=[
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fef2f2")),
                    ("BOX", (0, 0), (-1, -1), 0.5, self.C_SEV_CRITICAL),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ],
            )
            left_cell_elements.extend([Spacer(1, 6), penalty_box])
        else:
            clean_status = Table(
                [[Paragraph("Standard Weighting Applied (No Dynamic Penalties)", ParagraphStyle("ClnTxt", parent=self.style_body, textColor=self.C_SEV_PASS, fontSize=7.5, leading=9.5))]],
                colWidths=[180],
                style=[
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0fdf4")),
                    ("BOX", (0, 0), (-1, -1), 0.5, self.C_SEV_PASS),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ],
            )
            left_cell_elements.extend([Spacer(1, 6), clean_status])

        # Right Column: Four Vectors Breakdown Table
        safety_sc = float(rqi_info.get("safety_score", 100.0))
        perf_sc = float(rqi_info.get("performance_score", 100.0))
        maint_sc = float(rqi_info.get("maintainability_score", 100.0))
        sec_sc = float(rqi_info.get("security_score", 100.0))

        vector_headers = ["Vector Dimension", "Weight", "Score", "Weighted Pts", "Status"]
        vector_rows = [
            [Paragraph(f"<b>{h}</b>", self.style_table_head) for h in vector_headers]
        ]

        vectors_meta = [
            ("Memory & Concurrency Safety", "30%", safety_sc, 0.30 * safety_sc),
            ("Performance & Allocation", "25%", perf_sc, 0.25 * perf_sc),
            ("Maintainability & Idiomatic", "25%", maint_sc, 0.25 * maint_sc),
            ("Security & Vulnerabilities", "20%", sec_sc, 0.20 * sec_sc),
        ]

        for name, weight, score, weighted in vectors_meta:
            if score >= 85:
                status_str = "<font color='#16a34a'><b>Optimal</b></font>"
            elif score >= 70:
                status_str = "<font color='#0284c7'><b>Acceptable</b></font>"
            elif score >= 50:
                status_str = "<font color='#d97706'><b>Warning</b></font>"
            else:
                status_str = "<font color='#dc2626'><b>Critical</b></font>"

            vector_rows.append([
                Paragraph(name, self.style_table_cell),
                Paragraph(weight, self.style_table_cell),
                Paragraph(f"{score:.1f}", self.style_table_cell),
                Paragraph(f"{weighted:.2f}", self.style_table_cell),
                Paragraph(status_str, self.style_table_cell),
            ])

        vector_table = Table(
            vector_rows,
            colWidths=[120, 45, 45, 60, 60],
            style=[
                ("BACKGROUND", (0, 0), (-1, 0), self.C_SECONDARY),
                ("GRID", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [self.C_WHITE, self.C_LIGHT_BG]),
            ],
        )

        composite_grid = Table(
            [[left_cell_elements, vector_table]],
            colWidths=[195, 345],
            style=[
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ],
        )

        return [
            Paragraph("Executive Scorecard & Quality Vector Matrix", self.style_section_heading),
            Spacer(1, 4),
            composite_grid,
        ]

    def _build_cwe_summary_strip(
        self, cwe_summary: Dict[str, Any], cwe_tags: List[Dict[str, Any]]
    ) -> List[Any]:
        """Creates the MITRE CWE Weakness status counter bar."""
        total = cwe_summary.get("total", len(cwe_tags))
        crit = cwe_summary.get("critical", 0)
        high = cwe_summary.get("high", 0)
        med = cwe_summary.get("medium", 0)
        low = cwe_summary.get("low", 0)

        # Count directly from tags if summary was empty
        if total == 0 and len(cwe_tags) > 0:
            total = len(cwe_tags)
            for t in cwe_tags:
                s = str(t.get("severity", "")).lower()
                if s == "critical":
                    crit += 1
                elif s == "high":
                    high += 1
                elif s == "medium":
                    med += 1
                elif s == "low":
                    low += 1

        strip_data = [
            [
                Paragraph("<b>TOTAL WEAKNESSES</b>", self.style_meta_label),
                Paragraph("<b>CRITICAL (SEV 1)</b>", self.style_meta_label),
                Paragraph("<b>HIGH (SEV 2)</b>", self.style_meta_label),
                Paragraph("<b>MEDIUM (SEV 3)</b>", self.style_meta_label),
                Paragraph("<b>LOW (SEV 4)</b>", self.style_meta_label),
            ],
            [
                Paragraph(f"<font size=13 color='#0f172a'><b>{total}</b></font>", self.style_body),
                Paragraph(f"<font size=13 color='#b91c1c'><b>{crit}</b></font>", self.style_body),
                Paragraph(f"<font size=13 color='#c2410c'><b>{high}</b></font>", self.style_body),
                Paragraph(f"<font size=13 color='#b45309'><b>{med}</b></font>", self.style_body),
                Paragraph(f"<font size=13 color='#2563eb'><b>{low}</b></font>", self.style_body),
            ],
        ]

        strip_table = Table(
            strip_data,
            colWidths=[108, 108, 108, 108, 108],
            style=[
                ("BACKGROUND", (0, 0), (-1, -1), self.C_LIGHT_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ],
        )

        return [
            Paragraph("MITRE CWE Weaknesses Summary", self.style_section_heading),
            Spacer(1, 4),
            strip_table,
        ]

    def _build_deductions_catalog(
        self, rqi_info: Dict[str, Any], cwe_tags: List[Dict[str, Any]]
    ) -> List[Any]:
        """Renders the detailed list of quality deductions with statement line numbers and remediation."""
        story = [
            Paragraph("Quality Deductions & Weakness Catalog", self.style_section_heading),
            Spacer(1, 4),
        ]

        # Collect deductions from structured_deductions_list or cwe_tags or raw deductions
        deductions = rqi_info.get("structured_deductions_list", [])
        if not deductions and cwe_tags:
            deductions = cwe_tags

        if not deductions:
            # Clean audit notice
            clean_box = Table(
                [
                    [
                        Paragraph(
                            "<b>Clean Quality Audit:</b> Zero CWE defects or vector deductions detected. "
                            "Subroutine conforms to idiomatic Rust ownership, borrowing, and safety patterns.",
                            ParagraphStyle("CleanPass", parent=self.style_body, textColor=self.C_SEV_PASS),
                        )
                    ]
                ],
                colWidths=[540],
                style=[
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0fdf4")),
                    ("BOX", (0, 0), (-1, -1), 0.75, self.C_SEV_PASS),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ],
            )
            story.append(clean_box)
            return story

        # Render each deduction in an executive card
        for i, d in enumerate(deductions):
            cwe_id = d.get("cwe_id") or "CWE-General"
            cwe_name = d.get("cwe_name") or d.get("name") or "Quality Deduction"
            sev = d.get("severity", "MEDIUM").upper()
            sev_color = self._get_severity_color(sev)
            line_no = d.get("line_number")
            line_str = f"Line {line_no}" if line_no else "Global Scope"
            penalty = d.get("penalty", 0.0)
            vector_name = str(d.get("vector", "General")).capitalize()
            msg = d.get("message") or d.get("description") or "Code defect identified."
            stmt = d.get("statement_code")
            remediation = d.get("remediation")

            # Header row
            header_left = Paragraph(
                f"<b>[{self._safe_text(cwe_id)}]</b> {self._safe_text(cwe_name)}",
                self.style_body_bold,
            )
            header_right = Paragraph(
                f"<b>{self._safe_text(sev)}</b> | {line_str} | <font color='#b91c1c'>-{penalty:.1f} pts</font>",
                ParagraphStyle("HRight", parent=self.style_body, alignment=2),
            )

            card_rows = [
                [header_left, header_right],
            ]

            # Vector category and description
            desc_text = f"<b>Dimension:</b> {vector_name} &nbsp;|&nbsp; <b>Finding:</b> {self._safe_text(msg)}"
            card_rows.append([
                Paragraph(desc_text, self.style_body),
                Paragraph("", self.style_body),
            ])

            # Affected code if available
            if stmt:
                code_p = Paragraph(
                    f"<b>Statement:</b> <code>{self._safe_text(stmt.strip())}</code>",
                    self.style_code,
                )
                card_rows.append([code_p, Paragraph("", self.style_body)])

            # Remediation guidance
            if remediation:
                rem_p = Paragraph(
                    f"<b>Remediation Guidance:</b> {self._safe_text(remediation)}",
                    self.style_remediation,
                )
                card_rows.append([rem_p, Paragraph("", self.style_body)])

            table_styles = [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, self.C_BORDER),
                ("SPAN", (0, 1), (1, 1)),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOX", (0, 0), (-1, -1), 0.5, sev_color),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]

            curr_row = 2
            if stmt:
                table_styles.append(("SPAN", (0, curr_row), (1, curr_row)))
                curr_row += 1
            if remediation:
                table_styles.append(("SPAN", (0, curr_row), (1, curr_row)))
                table_styles.append(("BACKGROUND", (0, curr_row), (1, curr_row), colors.HexColor("#f0f9ff")))
                curr_row += 1

            deduction_card = Table(
                card_rows,
                colWidths=[370, 170],
                style=table_styles,
            )

            story.append(KeepTogether([deduction_card, Spacer(1, 6)]))

        return story

    def _build_cpg_metrics_section(
        self, cpg_summary: Dict[str, Any], fn_data: Dict[str, Any]
    ) -> List[Any]:
        """Renders graph topology and AST/CFG/FLOG structural metrics."""
        metrics = fn_data.get("metrics", {})

        ast_nodes = cpg_summary.get("ast_nodes", 0)
        ast_edges = cpg_summary.get("ast_edges", 0)
        cfg_nodes = cpg_summary.get("cfg_nodes", 0)
        cfg_edges = cpg_summary.get("cfg_edges", 0)
        cyclomatic = cpg_summary.get("cyclomatic_complexity", 1)
        flog_nodes = cpg_summary.get("flog_nodes", 0)
        flog_edges = cpg_summary.get("flog_edges", 0)
        cpg_nodes = cpg_summary.get("cpg_nodes", 0)
        cpg_edges = cpg_summary.get("cpg_edges", 0)

        clones = metrics.get("clone_count", 0)
        allocs = metrics.get("allocation_count", 0)
        unsafes = metrics.get("unsafe_block_count", 0)
        borrows = metrics.get("borrow_count", 0)
        branches = metrics.get("branch_count", 0)

        topology_headers = ["CPG Layer / Graph Dimension", "Nodes", "Edges / Density", "Complexity Metric", "Value"]
        rows = [
            [Paragraph(f"<b>{h}</b>", self.style_table_head) for h in topology_headers],
            [
                Paragraph("Abstract Syntax Tree (AST)", self.style_table_cell),
                Paragraph(str(ast_nodes), self.style_table_cell),
                Paragraph(str(ast_edges), self.style_table_cell),
                Paragraph("Branches / Loops", self.style_table_cell),
                Paragraph(f"{branches} branches", self.style_table_cell),
            ],
            [
                Paragraph("Control Flow Graph (CFG)", self.style_table_cell),
                Paragraph(str(cfg_nodes), self.style_table_cell),
                Paragraph(str(cfg_edges), self.style_table_cell),
                Paragraph("Cyclomatic Complexity V(G)", self.style_table_cell),
                Paragraph(f"<b>{cyclomatic}</b>", self.style_table_cell),
            ],
            [
                Paragraph("Function-Level Ownership Graph (FLOG)", self.style_table_cell),
                Paragraph(str(flog_nodes), self.style_table_cell),
                Paragraph(str(flog_edges), self.style_table_cell),
                Paragraph("Heap Allocations & Clones", self.style_table_cell),
                Paragraph(f"{allocs} allocs, {clones} clones", self.style_table_cell),
            ],
            [
                Paragraph("Unified Code Property Graph (CPG)", self.style_table_cell),
                Paragraph(str(cpg_nodes), self.style_table_cell),
                Paragraph(str(cpg_edges), self.style_table_cell),
                Paragraph("Unsafe Blocks & Borrows", self.style_table_cell),
                Paragraph(f"{unsafes} unsafe, {borrows} borrows", self.style_table_cell),
            ],
        ]

        table = Table(
            rows,
            colWidths=[170, 60, 90, 130, 90],
            style=[
                ("BACKGROUND", (0, 0), (-1, 0), self.C_SECONDARY),
                ("GRID", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [self.C_WHITE, self.C_LIGHT_BG]),
            ],
        )

        return [
            Paragraph("Graph Topology & Code Property Graph (CPG) Metrics", self.style_section_heading),
            Spacer(1, 4),
            table,
        ]

    def _build_xai_section(self, xai_report: Dict[str, Any]) -> List[Any]:
        """Renders Explainable AI (XAI) diagnosis and refactoring patch candidate."""
        explanation = xai_report.get("explanation", "")
        refactored_code = xai_report.get("refactored_code", "")

        story = [
            Paragraph("Explainable AI (XAI) Root Cause Diagnosis & Remediation Candidate", self.style_section_heading),
            Spacer(1, 4),
        ]

        if explanation:
            safe_exp = self._safe_text(explanation).replace("\n", "<br/>")
            exp_table = Table(
                [
                    [
                        Paragraph(
                            f"<b>AI Architectural Diagnosis:</b><br/>{safe_exp}",
                            self.style_body,
                        )
                    ]
                ],
                colWidths=[540],
                style=[
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                    ("BOX", (0, 0), (-1, -1), 0.5, self.C_ACCENT),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ],
            )
            story.append(exp_table)
            story.append(Spacer(1, 8))

        if refactored_code:
            safe_code = self._safe_text(refactored_code).replace("\n", "<br/>").replace(" ", "&nbsp;")
            code_table = Table(
                [
                    [Paragraph("<b>Idiomatic Refactored Patch Candidate:</b>", self.style_meta_label)],
                    [Paragraph(f"<code>{safe_code}</code>", self.style_code)],
                ],
                colWidths=[540],
                style=[
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                    ("BOX", (0, 0), (-1, -1), 0.5, self.C_BORDER),
                    ("LINEBELOW", (0, 0), (-1, 0), 0.5, self.C_BORDER),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ],
            )
            story.append(KeepTogether([code_table, Spacer(1, 8)]))

        return story


def generate_pdf_report(
    audit_data: Dict[str, Any],
    filename: Optional[str] = None,
    source_code: Optional[str] = None,
) -> bytes:
    """Convenience functional interface to generate PDF report."""
    generator = RustAuditPDFReportGenerator()
    return generator.generate(audit_data, filename=filename, source_code=source_code)
